spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
recipai:
  meal-plan:
    max-owned-plans: 5
  s3:
    presigned-url-expiration-minutes: 10